services:
  db:
    container_name: database
    image: postgres:16.1-alpine3.18
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=user
    ports:
      - 5432:5432
